#CALCULAR EL AREA DE UN TRIANGULO RECTANGULO

# IMPORTAR LIBRERIA QUE ME PERMITE UTILIZAR ACCIONES DEL SISTEMA OPERATIVO COMO LIMPIAR PANTALLA
import os
os.system('cls')

# SOLICITAR DATOS DE ENTRADA CON input() Y CONVERTIRLOS A NATURALEZA NUMERICA (ENTERO - DECIMAL)
# SE CONVIERTEN A NUMERICOS PARA PODER APLICAR OPERACIONES ARITMETICAS
# input() ... PERMITE INGRESAR DATOS POR TECLADO ... ojo INGRESAN TIPO STRING
# int() ... CONVIERTE DATOS STRING A NUMERICOS ENTEROS
base=int(input("Digite valor de la base: "))
altura=int(input("Digite valor de la altura: "))

# REALIZAR PROCESOS ... OPERACIONES ARITMETICAS
area=base*altura/2

# PRESENTAR DATOS DE SALIDA CON print()

print("el valor del area es: "+str(area))